pollapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from polls import urls as polls_url
from polls.views import IndexView


urlpatterns = [
	url(r'^polls/', include(polls_url)),
    url(r'^$', IndexView.as_view(), name='home'),
	url(r'^login/$', auth_views.login, name='login'),
	url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url, include
from . import views
from .views import ProfileCreateView, IndexView, DetailView, result_minority_north_east



app_name = 'polls'

urlpatterns = [
	url(r'^create_profile/$', ProfileCreateView.as_view(), name='create_profile'),
	url(r'^(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
	#url(r'^(?P<pk>\d+)/result/$', ResultView.as_view(), name='result'),
	url(r'^(?P<poll_id>\d+)/result_all/$', views.result_all, name='result_all'),
	url(r'^(?P<poll_id>\d+)/result_male/$', views.result_male, name='result_male'),
	url(r'^(?P<poll_id>\d+)/result_female/$', views.result_female, name='result_female'),
	url(r'^(?P<poll_id>\d+)/result_age_18_24/$', views.result_age_18_24, name='result_age_18_24'),
	url(r'^(?P<poll_id>\d+)/result_age_25_34/$', views.result_age_25_34, name='result_age_25_34'),
	url(r'^(?P<poll_id>\d+)/result_age_35_44/$', views.result_age_35_44, name='result_age_35_44'),
	url(r'^(?P<poll_id>\d+)/result_age_45_54/$', views.result_age_45_54, name='result_age_45_54'),
	url(r'^(?P<poll_id>\d+)/result_age_55_64/$', views.result_age_55_64, name='result_age_55_64'),
	url(r'^(?P<poll_id>\d+)/result_age_65_/$', views.result_age_65_, name='result_age_65_'),
	url(r'^(?P<poll_id>\d+)/result_hausa_fulani/$', views.result_hausa_fulani, name='result_hausa_fulani'),
	url(r'^(?P<poll_id>\d+)/result_igbo/$', views.result_igbo, name='result_igbo'),
	url(r'^(?P<poll_id>\d+)/result_yoruba/$', views.result_yoruba, name='result_yoruba'),
	url(r'^(?P<poll_id>\d+)/result_minority_south_south/$', views.result_minority_south_south, name='result_minority_south_south'),
	url(r'^(?P<poll_id>\d+)/result_minority_north_central/$', views.result_minority_north_central, name='result_minority_north_central'),
	url(r'^(?P<poll_id>\d+)/result_minority_north_east/$', views.result_minority_north_east, name='result_minority_north_east'),
	url(r'^(?P<poll_id>\d+)/result_north_west/$', views.result_north_west, name='result_north_west'),
	url(r'^(?P<poll_id>\d+)/result_north_east/$', views.result_north_east, name='result_north_east'),
	url(r'^(?P<poll_id>\d+)/result_north_central/$', views.result_north_central, name='result_north_central'),
	url(r'^(?P<poll_id>\d+)/result_south_west/$', views.result_south_west, name='result_south_west'),
	url(r'^(?P<poll_id>\d+)/result_south_east/$', views.result_south_east, name='result_south_east'),
	url(r'^(?P<poll_id>\d+)/result_south_south/$', views.result_south_south, name='result_south_south'),
	url(r'^(?P<poll_id>\d+)/result_diaspora/$', views.result_diaspora, name='result_diaspora'),
	url(r'^(?P<poll_id>\d+)/result_less_secondary/$', views.result_less_secondary, name='result_less_secondary'),
	url(r'^(?P<poll_id>\d+)/result_secondary/$', views.result_secondary, name='result_secondary'),
	url(r'^(?P<poll_id>\d+)/result_graduate/$', views.result_graduate, name='result_graduate'),
	url(r'^(?P<poll_id>\d+)/result_postgraduate/$', views.result_postgraduate, name='result_postgraduate'),
	url(r'^(?P<poll_id>\d+)/result_currently_unemployed/$', views.result_currently_unemployed, name='result_currently_unemployed'),
	url(r'^(?P<poll_id>\d+)/result_employed_full_time/$', views.result_employed_full_time, name='result_employed_full_time'),
	url(r'^(?P<poll_id>\d+)/result_employed_part_time/$', views.result_employed_part_time, name='result_employed_part_time'),
	url(r'^(?P<poll_id>\d+)/result_self_employed/$', views.result_self_employed, name='result_self_employed'),
	url(r'^(?P<poll_id>\d+)/result_student/$', views.result_student, name='result_student'),
	url(r'^(?P<poll_id>\d+)/result_retired/$', views.result_retired, name='result_retired'),
	url(r'^(?P<poll_id>\d+)/result_less_18000/$', views.result_less_18000, name='result_less_18000'),
	url(r'^(?P<poll_id>\d+)/result_18000_50000/$', views.result_18000_50000, name='result_18000_50000'),
	url(r'^(?P<poll_id>\d+)/result_51000_100000/$', views.result_51000_100000, name='result_51000_100000'),
	url(r'^(?P<poll_id>\d+)/result_101000_200000/$', views.result_101000_200000, name='result_101000_200000'),
	url(r'^(?P<poll_id>\d+)/result_201000_500000/$', views.result_201000_500000, name='result_201000_500000'),
	url(r'^(?P<poll_id>\d+)/result_500000/$', views.result_500000, name='result_500000'),
	url(r'^(?P<poll_id>\d+)/result_single_never_married/$', views.result_single_never_married, name='result_single_never_married'),
	url(r'^(?P<poll_id>\d+)/result_divorced_separated/$', views.result_divorced_separated, name='result_divorced_separated'),
	url(r'^(?P<poll_id>\d+)/result_married/$', views.result_married, name='result_married'),
	url(r'^(?P<poll_id>\d+)/result_widowed/$', views.result_widowed, name='result_widowed'),
	url(r'^(?P<poll_id>\d+)/result_christianity/$', views.result_christianity, name='result_christianity'),
	url(r'^(?P<poll_id>\d+)/result_islam/$', views.result_islam, name='result_islam'),
	url(r'^(?P<poll_id>\d+)/result_other_religion/$', views.result_other_religion, name='result_other_religion'),
	url(r'^$', IndexView.as_view(), name='index'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<poll_id>\d+)/respondents/$', views.respondents, name='respondents'),
]

polls/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    sex = models.CharField(max_length=7, choices=sex, blank=False)
    age = (
        ('18-24', '18-24'),
        ('25-34', '25-34'),
        ('35-44', '35-44'),
        ('45-54', '45-54'),
        ('55-64', '55-64'),
        ('65+', '65+'),
    )

    age = models.CharField(max_length=10, choices=age, blank=False)
    ethnicity = (
        ('Hausa/Fulani', 'Hausa/Fulani'),
        ('Igbo', 'Igbo'),
        ('Yoruba', 'Yoruba'),
        ('Minority-South South', 'Minority-South South'),
        ('Minority-North Central', 'Minority-North Central'),
        ('Minority-North East', 'Minority-North East'),
    )

    ethnicity = models.CharField(max_length=30, choices=ethnicity, blank=False)
    residence = (
        ('North West', 'North West'),
        ('North East', 'North East'),
        ('North Central', 'North Central'),
        ('South West', 'South West'),
        ('South East', 'South East'),
        ('South South', 'South South'),
        ('Diaspora', 'Diaspora'),
    )

    residence = models.CharField(max_length=20, choices=residence, blank=False)
    education = (
        ('Less than secondary school', 'Less than secondary school'),
        ('Secondary school', 'Secondary school'),
        ('Graduate', 'Graduate'),
        ('Post graduate', 'Post graduate'),
    )

    education = models.CharField(max_length=50, choices=education, blank=False)
    employment = (
        ('Currently unemployed', 'Currently unemployed'),
        ('Employed full time', 'Employed full time'),
        ('Employed part time', 'Employed part time'),
        ('Self employed', 'Self employed'),
        ('Student', 'Student'),
        ('Retired', 'Retired'),
    )

    employment = models.CharField(max_length=30, choices=employment, blank=False)
    income = (
        ('Less than 18,000', 'Less than 18,000'),
        ('18,000 - 50,000', '18,000 - 50,000'),
        ('51,000 - 100,000', '51,000 - 100,000'),
        ('101,000 - 200,000', '101,000 - 200,000'),
        ('201,000 - 500,000', '201,000 - 500,000'),
        ('500,000+', '500,000+'),
    )

    income = models.CharField(max_length=30, choices=income, blank=False)
    marital_status = (
        ('Single-never married', 'Single-never married'),
        ('Divorced or Separated', 'Divorced or Separated'),
        ('Married', 'Married'),
        ('Widowed', 'Widowed'),
    )

    marital_status = models.CharField(max_length=30, choices=marital_status, blank=False)
    religion = (
        ('Christianity', 'Christianity'),
        ('Islam', 'Islam'),
        ('Other', 'Other'),
    )

    religion = models.CharField(max_length=20, choices=religion, blank=False)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    

    @receiver(post_save, sender=user)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
    
    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=user)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Poll(models.Model):
    question = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    user = models.ManyToManyField(User)
    profile = models.ManyToManyField(Profile)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ["-created"]



class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    profile = models.ManyToManyField(Profile)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile


class ProfileForm(forms.ModelForm):
	class Meta:
		model 	= Profile
		exclude = ['user', 'created', 'updated']

polls/templates/polls/_101000_200000.html
{% load polls_filters %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>{% block title %}{% endblock %} Nigeria Online Polls</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- bootstrap cdn -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<!-- Custom Fonts -->
  <link href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">

  <!-- Google fonts - Open Sans-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">

  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/green.css' %}">
    
  <!-- Favicon-->
  <link rel="shortcut icon" href="favicon.png">
</head>
<body style="background-color: #e5ffe5 !important;">
	<header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{% url 'home' %}" class="navbar-left"><img src="{% static 'img/pollit_logo.png' %}" width="50"></a>
      </nav>
    </header>

<div style="margin-bottom: 50px; margin-top: 50px;" class="container">
	<div class="row">
		<div style="padding: 20px;" class="col-md-6">
			<div style="margin-bottom: 50px;">
				<h3>{{ poll.question }}</h3>
			</div>
			<div>
				<canvas id="myChart" width="300" height="200"></canvas>
			</div>
			<div style="margin-top: 50px;">
				{% for choice in choices %}
				<ul>
    				<li style="margin-bottom: 10px;" class="btn btn-outline-success btn-sm">{{ choice.choice_text }} -- <b>{{ choice.profile.count|_101000_200000_percentage:choice.id }}%</b>
    				</li>
				</ul>
				{% endfor %}
			</div>
		</div>
		<div class="col-md-6">
			<div style="background-color: #ffffff; border: 1px solid green; border-radius: 5px; padding: 20px;">
				<h3 style="margin: 20px;">Filter Votes </h3>
				<p class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_all' poll.id %}">All</a></p>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Sex</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_male' poll.id %}">Male</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_female' poll.id %}">Female</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Age</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_18_24' poll.id %}">18-24</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_25_34' poll.id %}">25-34</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_35_44' poll.id %}">35-44</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_45_54' poll.id %}">45-54</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_55_64' poll.id %}">55-64</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_age_65_' poll.id %}">65+</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Ethnicity</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_hausa_fulani' poll.id %}">Hausa/Fulani</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_igbo' poll.id %}">Igbo</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_yoruba' poll.id %}">Yoruba</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_minority_south_south' poll.id %}">Minority SS</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_minority_north_central' poll.id %}">Minority NC</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_minority_north_east' poll.id %}">Minority NE</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Residence</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_north_west' poll.id %}">North West</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_north_east' poll.id %}">North East</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_north_central' poll.id %}">North Central</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_south_west' poll.id %}">South West</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_south_east' poll.id %}">South East</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_south_south' poll.id %}">South South</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_diaspora' poll.id %}">Diaspora</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Education</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_less_secondary' poll.id %}">Below Secondary</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_secondary' poll.id %}">Secondary</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_graduate' poll.id %}">Graduate</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_postgraduate' poll.id %}">Postgraduate</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Employment</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_currently_unemployed' poll.id %}">Currently unemployed</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_employed_full_time' poll.id %}">Employed full time</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_employed_part_time' poll.id %}">Employed part time</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_self_employed' poll.id %}">Self employed</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_student' poll.id %}">Student</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_retired' poll.id %}">Retired</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Income</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_less_18000' poll.id %}">below 18,000</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_18000_50000' poll.id %}">18,000-50,000</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_51000_100000' poll.id %}">51,000-100,000</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success active btn-sm" href="{% url 'polls:result_101000_200000' poll.id %}">101,000-200,000</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_201000_500000' poll.id %}">201,000-500,000</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_500000' poll.id %}">500,000+</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Marital Status</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_single_never_married' poll.id %}">Single never married</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_divorced_separated' poll.id %}">Divorced or Separated</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_married' poll.id %}">Married</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_widowed' poll.id %}">Widowed</a></li>
				</ul>
				<p style="margin-bottom: 0; margin-top: 10px; border-bottom: 1px solid green">Religion</p>
				<ul style="margin-top: 5px;" class="list-inline">
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_christianity' poll.id %}">Christianity</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_islam' poll.id %}">Islam</a></li>
					<li class="list-inline-item"><a class="btn btn-outline-success btn-sm" href="{% url 'polls:result_other_religion' poll.id %}">Others</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
 <footer style="background-color: #ffffff !important;">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/PollitNigeria">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://web.facebook.com/pollitnigeria/">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://plus.google.com/u/0/103743218975552519138">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; www.pollitnigeria.com 2018</p>
          </div>
        </div>
      </div>
    </footer>

<!--jquery cdn-->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<script src="{% static 'js/Chart.min.js' %}"></script>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
        labels: [{% for choice in choices %}'{{ choice.choice_text }}', {% endfor %}],
        datasets: [{
            label: '# of Votes',
            data: [{% for choice in choices %} {{ choice.profile.count|_101000_200000_votes:choice.id }}, {% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            xAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
</body>
</html>

polls/templates/polls/create_profile.html
{% extends 'polls/base.html' %}

{% load bootstrap3 %}
{% load bootstrap %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block title %}{{ user }} Profile | {{ block.super }}{% endblock %}

{% block content %}
<div style="margin-bottom: 100px; margin-top: 50px;" class="row">
		<div style="margin-bottom: 20px;" class="col-md-8" class="form-group">
			{% if messages %}
			{% bootstrap_javascript jquery=1 %}
			{% bootstrap_messages %}
			{% endif %}
			<form method="POST" action="{% url 'polls:create_profile' %}" class="form">
			{{ form|bootstrap }}
			{% csrf_token %}
			<input type="submit" value="Create" class="btn btn-success"> 
			</form>
		</div>
		<div class="col-md-4">
			<div style="background-color: #ffffff; border: 1px solid green; border-radius: 5px; padding: 20px;">
				<h3 style="margin: 10px; text-align: center;">About</h3>
				{% load static %}
				<img src="{% static 'img/pollit_logo.png' %}" width=100%; height=100%;>
				<p>Pollit Nigeria conducts online opinion polls on relevant and critical national issues. Our goal is to ensure the voice of regular Nigerians gets heard. Our polls application allows you to both filter votes by respondents characteristics and also view the demography of respondents for every poll. The future of polling is online, and our methodology represents the best approach yet. </p>
			</div>
		</div>
</div>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div style="margin-bottom: 100px; margin-top: 50px;" class="row">
	{% if not user.profile %}
	<p>You must <a href="{% url 'polls:create_profile' %}">create</a> a profile to vote</p>
	{% endif %}
</div>
<div style="margin-bottom: 50px; margin-top: 50px;" class="row">
	<div class="col-md-8">
		<h3 style="margin-bottom: 50px;">{{ poll.question }}</h3>

		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<form action="{% url 'polls:vote' poll.id %}" method="post">
		{% csrf_token %}
		{% for choice in poll.choice_set.all %}
		    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
		    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<input style="margin-top: 50px; margin-bottom: 50px;" class="btn btn-outline-success btn-sm" type="submit" value="Vote" />
		</form>
	</div>
	<div class="col-md-4">
			<div style="background-color: #ffffff; border: 1px solid green; border-radius: 5px; padding: 20px;">
				<h3 style="margin: 10px; text-align: center;">About</h3>
				{% load static %}
				<img src="{% static 'img/pollit_logo.png' %}" width=100%; height=100%;>
				<p>Pollit Nigeria conducts online opinion polls on relevant and critical national issues. Our mission is to ensure the voice of regular Nigerians gets heard. Our polls application allows you to both filter votes by respondents characteristics and also view the demography of respondents for every poll. The future of polling is online, and our methodology represents the best approach yet. </p>
			</div>
		</div>
</div>
{% endblock %}